//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPasantia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relacion
    {
        public int IdRelacion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdDireccion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Direccione Direccione { get; set; }
    }
}
